services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: python:3.10-slim
    container_name: trumpgolftrack_bot
    command: /bin/sh -c "pip install --upgrade pip && pip install -r requirements.txt && python main.py"
    working_dir: /
    volumes:
      - ./:/bot:rw
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
