services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trumpgolftrack_bot
    working_dir: /bot
    volumes:
      - ./:/bot:rw
    command: /bin/sh -c "pip install --upgrade pip && pip install -r requirements.txt && python main.py"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
